apiVersion: apis.kcp.io/v1alpha1
kind: APIExport
metadata:
  creationTimestamp: null
  name: edge.kcp.io
spec:
  latestResourceSchemas:
  - v230622-6fbf5a92.customizers.edge.kcp.io
  - v230622-6fbf5a92.edgeplacements.edge.kcp.io
  - v230622-6fbf5a92.edgesyncconfigs.edge.kcp.io
  - v230622-6fbf5a92.singleplacementslices.edge.kcp.io
  - v230622-6fbf5a92.syncerconfigs.edge.kcp.io
status: {}
