apiVersion: apis.kcp.io/v1alpha1
kind: APIExport
metadata:
  creationTimestamp: null
  name: edge.kcp.io
spec:
  latestResourceSchemas:
  - v230622-758496a6.customizers.edge.kcp.io
  - v230622-758496a6.edgeplacements.edge.kcp.io
  - v230622-758496a6.edgesyncconfigs.edge.kcp.io
  - v230622-758496a6.singleplacementslices.edge.kcp.io
  - v230622-758496a6.syncerconfigs.edge.kcp.io
status: {}
