apiVersion: apis.kcp.io/v1alpha1
kind: APIExport
metadata:
  creationTimestamp: null
  name: edge.kcp.io
spec:
  latestResourceSchemas:
  - v230622-db17e114.customizers.edge.kcp.io
  - v230622-db17e114.edgeplacements.edge.kcp.io
  - v230622-db17e114.edgesyncconfigs.edge.kcp.io
  - v230622-db17e114.singleplacementslices.edge.kcp.io
  - v230622-db17e114.syncerconfigs.edge.kcp.io
status: {}
