apiVersion: apis.kcp.io/v1alpha1
kind: APIExport
metadata:
  creationTimestamp: null
  name: edge.kubestellar.io
spec:
  latestResourceSchemas:
  - v231005-c6f7728ef.customizers.edge.kubestellar.io
  - v231005-c6f7728ef.edgesyncconfigs.edge.kubestellar.io
  - v231005-c6f7728ef.locations.edge.kubestellar.io
  - v231005-c6f7728ef.syncerconfigs.edge.kubestellar.io
  - v231020-4e62eaf7.synctargets.edge.kubestellar.io
  - v231026-b37310b41.edgeplacements.edge.kubestellar.io
  - v231113-f0837626.singleplacementslices.edge.kubestellar.io
  - v231121-af7647486.downsyncworkloadpartslices.edge.kubestellar.io
status: {}
