apiVersion: apis.kcp.io/v1alpha1
kind: APIExport
metadata:
  creationTimestamp: null
  name: lc.kubestellar.io
spec:
  latestResourceSchemas:
  - v230622-758496a6.clusterproviderdescs.lc.kubestellar.io
  - v230622-758496a6.logicalclusters.lc.kubestellar.io
status: {}
